testclrBA<-read.csv(paste0("testclrBA.csv"))
testclrFU<-read.csv(paste0("testclrFU.csv"))
testclrPR<-read.csv(paste0("testclrPR.csv"))
par(mfrow=c(1,3))
plot(testclrBA[complete.cases(testclrBA),]$AB,testclrBA[complete.cases(testclrBA),]$clr,xlab="offsetted poisson model prediction quality",ylab="clr model prediction quality",main="Bacteria")
abline(a=0,b=1)
plot(testclrFU[complete.cases(testclrFU),]$AB,testclrFU[complete.cases(testclrFU),]$clr,xlab="offsetted poisson model prediction quality",ylab="clr model prediction quality",main="Fungi")
abline(a=0,b=1)
plot(testclrPR[complete.cases(testclrPR),]$AB,testclrPR[complete.cases(testclrPR),]$clr,xlab="offsetted poisson model prediction quality",ylab="clr model prediction quality",main="Protist")
abline(a=0,b=1)
par(mfrow=c(1,1))
png(file=paste0("figures/PAAB_selection/testmodels/plotTest100sp_clrVSpoisson",GtoM,".png"),res=300,width=1961,height=2000)
par(mfrow=c(1,3))
plot(testclrBA[complete.cases(testclrBA),]$AB,testclrBA[complete.cases(testclrBA),]$clr,xlab="offsetted poisson model prediction quality",ylab="clr model prediction quality",main="Bacteria")
abline(a=0,b=1)
plot(testclrFU[complete.cases(testclrFU),]$AB,testclrFU[complete.cases(testclrFU),]$clr,xlab="offsetted poisson model prediction quality",ylab="clr model prediction quality",main="Fungi")
abline(a=0,b=1)
plot(testclrPR[complete.cases(testclrPR),]$AB,testclrPR[complete.cases(testclrPR),]$clr,xlab="offsetted poisson model prediction quality",ylab="clr model prediction quality",main="Protist")
abline(a=0,b=1)
par(mfrow=c(1,1))
dev.off()